spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: api-1
          uri: lb://Welcome-service
          predicates:
            - Path=/welcome
        - id: api-2
          uri: lb://Greet-service
          predicates:
            - Path=/greet
